version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mayankthukral1810
      MONGO_INITDB_ROOT_PASSWORD: hello123  
    ports:
      - "27017:27017"

  # Node.js (Express) service
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    container_name: nodejs
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb+srv://mayankthukral1810:hello123@cluster0.zyjeuqn.mongodb.net/?retryWrites=true&w=majority
    ports:
      - "5000:5000"

  # React service
  react:
    build:
      context: ./client
      dockerfile: Dockerfile-react
    container_name: react
    depends_on:
      - nodejs
    environment:
      REACT_APP_API_URL: http://nodejs:5000
    ports:
      - "3000:3000"

  # Nginx service
  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - react
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
